collections:
  posts:
    permalink: /articles/:title/
themes:
  ruhoh-twitter:
    datamapper: 'ruhoh'
    pageLayout: 'page'
    postLayout: 'post'
  ruhoh-bootstrap-2:
    datamapper: 'ruhoh'
    pageLayout: '_root'
    postLayout: 'posts'
assets:
  media: {}
